### ISSUE TITLE
Chapter 05 - 01_backtest_with_trades: PicklingError: Can't pickle <enum 'ORDER STATUS'>: attribute lookup ORDER STATUS on zipline.finance.order failed

### ISSUE THREAD

**Issue by kmeans27** [stefan-jansen/machine-learning-for-trading#211]
PicklingError                             Traceback (most recent call last)
~\AppData\Local\Temp\tmpq2e3rzw0/ipykernel_15928/1782890004.py in <module>
      1 with pd.HDFStore('backtests.h5') as store:
----> 2     store.put('backtest/equal_weight', backtest)
      3     store.put('returns/equal_weight', returns)
      4     store.put('positions/equal_weight', positions)
      5     store.put('transactions/equal_weight', transactions)

C:\ProgramData\Anaconda3\envs\ml4t\lib\site-packages\pandas\io\pytables.py in put(self, key, value, format, index, append, complib, complevel, min_itemsize, nan_rep, data_columns, encoding, errors, track_times, dropna)
   1090             format = get_option("io.hdf.default_format") or "fixed"
   1091         format = self._validate_format(format)
-> 1092         self._write_to_group(
   1093             key,
   1094             value,

C:\ProgramData\Anaconda3\envs\ml4t\lib\site-packages\pandas\io\pytables.py in _write_to_group(self, key, value, format, axes, index, append, complib, complevel, fletcher32, min_itemsize, chunksize, expectedrows, dropna, nan_rep, data_columns, encoding, errors, track_times)
   1740 
   1741         # write the object
-> 1742         s.write(
   1743             obj=value,
   1744             axes=axes,

C:\ProgramData\Anaconda3\envs\ml4t\lib\site-packages\pandas\io\pytables.py in write(self, obj, **kwargs)
   3173             # I have no idea why, but writing values before items fixed #2299
   3174             blk_items = data.items.take(blk.mgr_locs)
-> 3175             self.write_array(f"block{i}_values", blk.values, items=blk_items)
   3176             self.write_index(f"block{i}_items", blk_items)
   3177 

C:\ProgramData\Anaconda3\envs\ml4t\lib\site-packages\pandas\io\pytables.py in write_array(self, key, obj, items)
   3031 
   3032             vlarr = self._handle.create_vlarray(self.group, key, _tables().ObjectAtom())
-> 3033             vlarr.append(value)
   3034 
   3035         elif is_datetime64_dtype(value.dtype):

C:\ProgramData\Anaconda3\envs\ml4t\lib\site-packages\tables\vlarray.py in append(self, sequence)
    523         atom = self.atom
    524         if not hasattr(atom, 'size'):  # it is a pseudo-atom
--> 525             sequence = atom.toarray(sequence)
    526             statom = atom.base
    527         else:

C:\ProgramData\Anaconda3\envs\ml4t\lib\site-packages\tables\atom.py in toarray(self, object_)
   1081 
   1082     def toarray(self, object_):
-> 1083         buffer_ = self._tobuffer(object_)
   1084         array = numpy.ndarray(buffer=buffer_, dtype=self.base.dtype,
   1085                               shape=len(buffer_))

C:\ProgramData\Anaconda3\envs\ml4t\lib\site-packages\tables\atom.py in _tobuffer(self, object_)
   1214 
   1215     def _tobuffer(self, object_):
-> 1216         return pickle.dumps(object_, pickle.HIGHEST_PROTOCOL)
   1217 
   1218     def fromarray(self, array):

PicklingError: Can't pickle <enum 'ORDER STATUS'>: attribute lookup ORDER STATUS on zipline.finance.order failed

**Comment by jrizcallah** [comment]
I am having the same issue, and it really derails the ability to move forward with exploring Pyfolio. Just leaving this comment here to see the solution later.

**Comment by MBounouar** [comment]
This should have been resolved in the latest release of zipline [zipline-reloaded #56](https://github.com/stefan-jansen/zipline-reloaded/commit/aa52ba31a37e5f4cbe0fc2ee6c64a8d9f6241045).
See also [#205](https://github.com/stefan-jansen/machine-learning-for-trading/issues/205)

**Comment by kmeans27** [comment]
Thank you for your reply. I still don't know what to do now. I created the environment from the .yml file & synced the files via github desktop

**Comment by MBounouar** [comment]
I have no experience with conda but you need to upgrade zipline-reloaded to version 2.2, maybe `conda install zipline-reloaded=2.2` ?

**Comment by stefan-jansen** [comment]
Thanks @MBounouar. @kmeans27, please see the beginning of the [installation instructions](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/installation#installation-instructions) that suggest you use environment file `installation/ml4t-base.yml` like so:

```bash
conda create -n ml4t python=3.8
mamba env update -n ml4t -f ml4t-base.yml
conda activate ml4t
```

to install the latest available version.

**Comment by n-oliver** [comment]
I have a miniconda config with ml4t already built, and ran into the pickle problem with the "buyapple" example from the documentation.
I tried:
conda deactivate
conda create -n ml4t python=3.8
mamba env update -n ml4t -f ml4t-base.yml
conda activate ml4t

This did not solve the problem.
I tried running the mamba update command with an activated ml4t environment.

This also did not solve the problem.

I tried "conda install zipline-reloaded=2.2", which failed because it could not find such a release.
